# Generated by Django 2.1.1 on 2018-12-03 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.TextField()),
                ('course_num', models.TextField()),
                ('lecture_hours', models.TextField()),
                ('lab_hours', models.TextField()),
                ('credit_hours', models.TextField()),
                ('date', models.TextField()),
                ('previous_version', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule_app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.Course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.TextField()),
                ('year', models.TextField()),
                ('name', models.TextField()),
                ('courses', models.ManyToManyField(through='schedule_app.Offering', to='schedule_app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='TermPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.Term')),
            ],
        ),
        migrations.AddField(
            model_name='offering',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.Term'),
        ),
    ]
