# Generated by Django 2.1.1 on 2018-12-06 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_num',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='lab_hours',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='lecture_hours',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='prefix',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schedule_app.Course'),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='term',
            name='semester',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='term',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
