# Generated by Django 2.1.1 on 2018-11-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
