# Generated by Django 2.1.1 on 2018-11-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule_app', '0004_delete_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('prefix', models.TextField()),
                ('course_num', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('professor', models.TextField()),
            ],
        ),
    ]
