# Generated by Django 2.1.1 on 2018-11-18 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0005_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
